version: '3'

services:
  mongodb:
    image: mongo:$MONGO_VERSION
    volumes:
      - ./mongodb:/data/db
    ports:
      - $MONGO_PORT:27017
  mysql:
    image: mysql:$MYSQL_VERSION
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - $MYSQL_PORT:3306
  www:
    image: nginx:$WWW_NGINX_VERSION
    volumes:
      - $WWW_ROOT:/usr/share/nginx/html
    ports:
      - $WWW_PORT:80
